#!/usr/bin/env bash

set -eux -o pipefail

REQUIRED_BUNDLER_VERSION="~> 1.14.3"

function update_rubygems() {
  gem update --system
}

function install_bundler() {
  gem install bundler --conservative --version "$REQUIRED_BUNDLER_VERSION"
}

function install_gems() {
  bundle check || bundle
}

function run_rake() {
  bundle exec rake
}

update_rubygems &&
install_bundler &&
install_gems &&
run_rake
